### PR TITLE
Offers limit parameter and offers double Quality cast

### PR DESCRIPTION
**Pull request by Platonenkov**
https://github.com/Transia-RnD/xrpl.c/issues/11

### CODE REVIEW

**Comment by dangell7** [comment]
Can you try updating all the decimal.parse with `NumberStyles.AllowExponent | NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture` no 'try'?

**Comment by dangell7** [comment]
Please try to break these up for easier review. Also notice the refactor on client. Enums go under transaction as well as interface and request/response.

https://github.com/Transia-RnD/xrpl.c/blob/main/Xrpl.C/Xrpl/Client/Models/Transaction/TrustSetTransaction.cs

**Comment by Platonenkov** [comment]
> Please try to break these up for easier review. Also notice the refactor on client. Enums go under transaction as well as interface and request/response.

sorry I don't understand

**Comment by dangell7** [comment]
> > Please try to break these up for easier review. Also notice the refactor on client. Enums go under transaction as well as interface and request/response.
> 
> sorry I don't understand

The Xrpl.C.Client has been refactored to match the XRPLF repositories so please note that change. And my other suggestion would be to break up your PR into smaller PR so they are easier for me to review.

**Comment by Platonenkov** [comment]
> The Xrpl.C.Client has been refactored to match the XRPLF repositories so please note that change. And my other suggestion would be to break up your PR into smaller PR so they are easier for me to review.

I think I will take your changes in the near future and try to do everything over again

**Pull request closed without merging**
