### PR TITLE
doc and subcribe func

### PR DESCRIPTION
**Pull request by Platonenkov**

### CODE REVIEW

**Comment by dangell7** [comment]
Can you also grab Subscribe and Unsubscribe?

**Comment by Platonenkov** [comment]
> 

what do you mean?
subscribe and usubscribe fuctions work
image

**Comment by dangell7** [comment]
This commit shows you edited the subscribe and unsubscribe methods...

https://github.com/Transia-RnD/XrplCSharp/commit/7a914aed86aae161ce61a4be0e87c38e44bd3e2d#diff-ea7380ef32fd3373e6ac12b0ea630550a2a839348892ce5ae17ed151992b6f93

I just want you to get credit for all your work.

**Comment by Platonenkov** [comment]
> This commit shows you edited the subscribe and unsubscribe methods...
> 
> [7a914ae#diff-ea7380ef32fd3373e6ac12b0ea630550a2a839348892ce5ae17ed151992b6f93](https://github.com/Transia-RnD/XrplCSharp/commit/7a914aed86aae161ce61a4be0e87c38e44bd3e2d#diff-ea7380ef32fd3373e6ac12b0ea630550a2a839348892ce5ae17ed151992b6f93)
> 
> I just want you to get credit for all your work.

Omg... Done

**Review by dangell7 — DISMISSED** [review]
We will resolve todos after. I want this moving for the refactor

**Review by dangell7 — DISMISSED** [review]

**Review by dangell7 — APPROVED** [review]

**Pull request merged**
